// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL8SUIdeLUoGG7v4kuST38-MZnL1pfqvQ',
    appId: '1:64899455216:web:0adf5528ab3779f07f8a35',
    messagingSenderId: '64899455216',
    projectId: 'todo-list-provider-8c843',
    authDomain: 'todo-list-provider-8c843.firebaseapp.com',
    storageBucket: 'todo-list-provider-8c843.appspot.com',
    measurementId: 'G-02X8FC4737',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARdXAutP5BF4IwKitRWK0w7NJbOxwqpgM',
    appId: '1:64899455216:android:c55969315ba6d8ad7f8a35',
    messagingSenderId: '64899455216',
    projectId: 'todo-list-provider-8c843',
    storageBucket: 'todo-list-provider-8c843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAitxIVfWb7gTCP75-5lsdXaYwdInipxN0',
    appId: '1:64899455216:ios:c34fb0db4bb67ab97f8a35',
    messagingSenderId: '64899455216',
    projectId: 'todo-list-provider-8c843',
    storageBucket: 'todo-list-provider-8c843.appspot.com',
    iosClientId: '64899455216-ic2d5lkafji0d4jh0ma1s34c9lfsr6bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProviderProject',
  );
}
